version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"  # Mapea el puerto 8000 interno del contenedor al 8001 de tu máquina
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evita sobrescribir node_modules
    ports:
      - "3001:3000"  # Mapea el puerto 3000 interno del contenedor al 3001 de tu máquina
    environment:
      - REACT_APP_API_URL=http://localhost:8001/api   #arreglar
# Conexión al backend
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
