version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"  # Puerto accesible desde la máquina host
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evita sobrescribir node_modules
    ports:
      - "3001:80"  # Nginx expone el puerto 80 como 3001 en el host
    environment:
      - REACT_APP_API_URL=http://backend:8000/api/  # Usar nombre del servicio "backend"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
