version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app_network
    command: "gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers=3"

  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/BaseDatos/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
