services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - django_network
    command: "python manage.py runserver 0.0.0.0:8000"


networks:
  django_network:
    driver: bridge
